# Dependencies
gems:             [jekyll-paginate, jekyll-gist]
markdown:         kramdown
highlighter:      rouge

# Settings
permalink:        pretty
paginate:         10
excerpt_separator: "<!--more-->" # this is currently not being used :(

# Site Metadata
title:            all the things
# tagline:          'Title tagline'
# description:      'Some stuff about stuff.'
url:              http://nbobhate.github.io
baseurl:          /
author:
  name:           'Nikitah Bobhate'
  url:            http://nbobhate.github.io

version:          2.1.0
github:
  repo:           https://github.com/nbobhate
