# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          all the things
paginate:       5
baseurl:        ""
url:            "http://nbobhate.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
kramdown:
  math_engine:  mathjax

# About
author:
  name:         Nikitah Bobhate
  url:          http://nbobhate.github.io

# Custom vars
version:        3.0.0
github:
  repo:         https://github.com/nbobhate

# Dependencies
plugins:
  - jekyll-paginate
